"""Headless component support.

A *headless component* is a multi-file component in the Basis convention whose
``.html`` template (± ``.css`` style) exist but whose ``.py`` logic file has not
been written yet. At mount time the VFS registry detects these and promotes them
to real, reactive :class:`Component` subclasses — markup becomes reactive with
no Python at all, and adding ``{stem}.py`` later "graduates" the component in
place: no renames (same class name, same tag, same import module name).

The client-side class is delivered as a *synthetic module*: generated source
served in-memory by the static handler (the pyc-mode pattern), advertised in the
PyScript VFS manifest, and pre-imported by the client entrypoint before mount.
"""

import re

from basis.shared.base_component import BaseComponent


def pascal(stem: str) -> str:
    """``todo_list`` -> ``TodoList`` (identifier-safe)."""
    parts = [p.capitalize() for p in re.split(r"[^0-9A-Za-z]+", stem) if p]
    name = "".join(parts) or "Component"
    if not name or not name[0].isidentifier() or name[0].isdigit():
        name = "_" + name
    return name


def kebab(stem: str) -> str:
    """``todo_list`` -> ``todo-list`` (the component's ``__tag__``)."""
    return stem.replace("_", "-")


def headless_module_name(mount_pkg: str, stem: str) -> str:
    """The synthetic module's dotted import name.

    Chosen to equal the module name a real ``{stem}.py`` would produce, so
    adding the ``.py`` later graduates the component with zero import churn.
    """
    return f"{mount_pkg}.{stem}" if mount_pkg else stem


def headless_identity(mount_pkg: str, stem: str) -> tuple[str, str, str]:
    """Return ``(class_name, tag, module_name)`` for a headless ``{stem}.html``."""
    return pascal(stem), kebab(stem), headless_module_name(mount_pkg, stem)


def build_headless_module_source(cls_name: str, tag: str, template: str, style: str) -> str:
    """Generate the synthetic client module source embedding template + style."""
    lines = [
        "# Generated by Basis — headless component (add a .py to graduate).",
        "from basis.shared.component import Component",
        "",
        f"class {cls_name}(Component):",
        f"    __tag__ = {tag!r}",
        f"    __headless__ = True",
        f"    template = {template!r}",
        f"    style = {style!r}",
    ]
    return "\n".join(lines) + "\n"


def create_headless_component(
    cls_name: str,
    tag: str,
    template: str,
    style: str,
    module_name: str,
):
    """Build + register the server-side headless Component subclass.

    Returns the class, or ``None`` when it cannot be promoted: empty template,
    malformed HTML, or the tag is already owned by a real (non-headless)
    component. A real component is never shadowed, and promotion is idempotent
    (an already-promoted headless class is returned as-is).
    """
    if not template or not template.strip():
        return None

    existing = BaseComponent._registry.get(tag)
    if existing is not None:
        if getattr(existing, "__headless__", False):
            return existing  # already promoted (idempotent re-mount)
        return None  # a real component owns this tag — never shadow it

    from basis.server.server_component import ServerComponent

    try:
        # Create under a real module so ``inspect.getfile(cls)`` works during
        # ``__init_subclass__`` (the synthetic module name is not importable on
        # the server), then re-tag it for HMR/identity matching.
        cls = type(
            cls_name,
            (ServerComponent,),
            {
                "__tag__": tag,
                "__headless__": True,
                "template": template,
                "style": style or "",
                "__module__": __name__,
            },
        )
    except Exception:
        return None
    cls.__module__ = module_name
    return cls


def refresh_headless_class(cls, template: str, style: str) -> None:
    """Point an existing headless class at new ``.html``/``.css`` content.

    Mirrors the work ``__init_subclass__`` does once, without re-registering the
    tag: rebuild the server blueprint + binding blueprints so the next SSR
    first-paint reflects an edit made during ``basis dev --hmr``. Failures are
    swallowed — the served synthetic source (hard-refresh path) is the source of
    truth and is updated separately.
    """
    try:
        cls.template = template
        cls.style = style or ""
        cls.__templatestr__ = template
        cls.__binding_blueprints__ = []
        cls._initialize_blueprint()
        cls._analyze_creation_args()
        cls._analyze_template()
    except Exception:
        pass


# Re-export for callers that only need the source-builder (e.g. tests).
__all__ = [
    "pascal",
    "kebab",
    "headless_module_name",
    "headless_identity",
    "build_headless_module_source",
    "create_headless_component",
    "refresh_headless_class",
]
